package cn.nnu.jyjs.etpweb.bean.Example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BlogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public BlogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBlogIdIsNull() {
            addCriterion("blogId is null");
            return (Criteria) this;
        }

        public Criteria andBlogIdIsNotNull() {
            addCriterion("blogId is not null");
            return (Criteria) this;
        }

        public Criteria andBlogIdEqualTo(Integer value) {
            addCriterion("blogId =", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdNotEqualTo(Integer value) {
            addCriterion("blogId <>", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdGreaterThan(Integer value) {
            addCriterion("blogId >", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("blogId >=", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdLessThan(Integer value) {
            addCriterion("blogId <", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdLessThanOrEqualTo(Integer value) {
            addCriterion("blogId <=", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdIn(List<Integer> values) {
            addCriterion("blogId in", values, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdNotIn(List<Integer> values) {
            addCriterion("blogId not in", values, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdBetween(Integer value1, Integer value2) {
            addCriterion("blogId between", value1, value2, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdNotBetween(Integer value1, Integer value2) {
            addCriterion("blogId not between", value1, value2, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogTitleIsNull() {
            addCriterion("blogTitle is null");
            return (Criteria) this;
        }

        public Criteria andBlogTitleIsNotNull() {
            addCriterion("blogTitle is not null");
            return (Criteria) this;
        }

        public Criteria andBlogTitleEqualTo(String value) {
            addCriterion("blogTitle =", value, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleNotEqualTo(String value) {
            addCriterion("blogTitle <>", value, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleGreaterThan(String value) {
            addCriterion("blogTitle >", value, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleGreaterThanOrEqualTo(String value) {
            addCriterion("blogTitle >=", value, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleLessThan(String value) {
            addCriterion("blogTitle <", value, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleLessThanOrEqualTo(String value) {
            addCriterion("blogTitle <=", value, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleLike(String value) {
            addCriterion("blogTitle like", value, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleNotLike(String value) {
            addCriterion("blogTitle not like", value, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleIn(List<String> values) {
            addCriterion("blogTitle in", values, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleNotIn(List<String> values) {
            addCriterion("blogTitle not in", values, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleBetween(String value1, String value2) {
            addCriterion("blogTitle between", value1, value2, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogTitleNotBetween(String value1, String value2) {
            addCriterion("blogTitle not between", value1, value2, "blogTitle");
            return (Criteria) this;
        }

        public Criteria andBlogStatusIsNull() {
            addCriterion("blogStatus is null");
            return (Criteria) this;
        }

        public Criteria andBlogStatusIsNotNull() {
            addCriterion("blogStatus is not null");
            return (Criteria) this;
        }

        public Criteria andBlogStatusEqualTo(Integer value) {
            addCriterion("blogStatus =", value, "blogStatus");
            return (Criteria) this;
        }

        public Criteria andBlogStatusNotEqualTo(Integer value) {
            addCriterion("blogStatus <>", value, "blogStatus");
            return (Criteria) this;
        }

        public Criteria andBlogStatusGreaterThan(Integer value) {
            addCriterion("blogStatus >", value, "blogStatus");
            return (Criteria) this;
        }

        public Criteria andBlogStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("blogStatus >=", value, "blogStatus");
            return (Criteria) this;
        }

        public Criteria andBlogStatusLessThan(Integer value) {
            addCriterion("blogStatus <", value, "blogStatus");
            return (Criteria) this;
        }

        public Criteria andBlogStatusLessThanOrEqualTo(Integer value) {
            addCriterion("blogStatus <=", value, "blogStatus");
            return (Criteria) this;
        }

        public Criteria andBlogStatusIn(List<Integer> values) {
            addCriterion("blogStatus in", values, "blogStatus");
            return (Criteria) this;
        }

        public Criteria andBlogStatusNotIn(List<Integer> values) {
            addCriterion("blogStatus not in", values, "blogStatus");
            return (Criteria) this;
        }

        public Criteria andBlogStatusBetween(Integer value1, Integer value2) {
            addCriterion("blogStatus between", value1, value2, "blogStatus");
            return (Criteria) this;
        }

        public Criteria andBlogStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("blogStatus not between", value1, value2, "blogStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("blogUpdateT is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("blogUpdateT is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("blogUpdateT =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("blogUpdateT <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("blogUpdateT >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("blogUpdateT >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("blogUpdateT <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("blogUpdateT <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("blogUpdateT in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("blogUpdateT not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("blogUpdateT between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("blogUpdateT not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andAuthorIdIsNull() {
            addCriterion("authorId is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIdIsNotNull() {
            addCriterion("authorId is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorIdEqualTo(Integer value) {
            addCriterion("authorId =", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdNotEqualTo(Integer value) {
            addCriterion("authorId <>", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdGreaterThan(Integer value) {
            addCriterion("authorId >", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("authorId >=", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdLessThan(Integer value) {
            addCriterion("authorId <", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdLessThanOrEqualTo(Integer value) {
            addCriterion("authorId <=", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdIn(List<Integer> values) {
            addCriterion("authorId in", values, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdNotIn(List<Integer> values) {
            addCriterion("authorId not in", values, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdBetween(Integer value1, Integer value2) {
            addCriterion("authorId between", value1, value2, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("authorId not between", value1, value2, "authorId");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractIsNull() {
            addCriterion("blogAbstract is null");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractIsNotNull() {
            addCriterion("blogAbstract is not null");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractEqualTo(String value) {
            addCriterion("blogAbstract =", value, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractNotEqualTo(String value) {
            addCriterion("blogAbstract <>", value, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractGreaterThan(String value) {
            addCriterion("blogAbstract >", value, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractGreaterThanOrEqualTo(String value) {
            addCriterion("blogAbstract >=", value, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractLessThan(String value) {
            addCriterion("blogAbstract <", value, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractLessThanOrEqualTo(String value) {
            addCriterion("blogAbstract <=", value, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractLike(String value) {
            addCriterion("blogAbstract like", value, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractNotLike(String value) {
            addCriterion("blogAbstract not like", value, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractIn(List<String> values) {
            addCriterion("blogAbstract in", values, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractNotIn(List<String> values) {
            addCriterion("blogAbstract not in", values, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractBetween(String value1, String value2) {
            addCriterion("blogAbstract between", value1, value2, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andBlogAbstractNotBetween(String value1, String value2) {
            addCriterion("blogAbstract not between", value1, value2, "blogAbstract");
            return (Criteria) this;
        }

        public Criteria andClickRateIsNull() {
            addCriterion("blogCTR is null");
            return (Criteria) this;
        }

        public Criteria andClickRateIsNotNull() {
            addCriterion("blogCTR is not null");
            return (Criteria) this;
        }

        public Criteria andClickRateEqualTo(Integer value) {
            addCriterion("blogCTR =", value, "clickRate");
            return (Criteria) this;
        }

        public Criteria andClickRateNotEqualTo(Integer value) {
            addCriterion("blogCTR <>", value, "clickRate");
            return (Criteria) this;
        }

        public Criteria andClickRateGreaterThan(Integer value) {
            addCriterion("blogCTR >", value, "clickRate");
            return (Criteria) this;
        }

        public Criteria andClickRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("blogCTR >=", value, "clickRate");
            return (Criteria) this;
        }

        public Criteria andClickRateLessThan(Integer value) {
            addCriterion("blogCTR <", value, "clickRate");
            return (Criteria) this;
        }

        public Criteria andClickRateLessThanOrEqualTo(Integer value) {
            addCriterion("blogCTR <=", value, "clickRate");
            return (Criteria) this;
        }

        public Criteria andClickRateIn(List<Integer> values) {
            addCriterion("blogCTR in", values, "clickRate");
            return (Criteria) this;
        }

        public Criteria andClickRateNotIn(List<Integer> values) {
            addCriterion("blogCTR not in", values, "clickRate");
            return (Criteria) this;
        }

        public Criteria andClickRateBetween(Integer value1, Integer value2) {
            addCriterion("blogCTR between", value1, value2, "clickRate");
            return (Criteria) this;
        }

        public Criteria andClickRateNotBetween(Integer value1, Integer value2) {
            addCriterion("blogCTR not between", value1, value2, "clickRate");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryIsNull() {
            addCriterion("blogCalegory is null");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryIsNotNull() {
            addCriterion("blogCalegory is not null");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryEqualTo(Integer value) {
            addCriterion("blogCalegory =", value, "blogCalegory");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryNotEqualTo(Integer value) {
            addCriterion("blogCalegory <>", value, "blogCalegory");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryGreaterThan(Integer value) {
            addCriterion("blogCalegory >", value, "blogCalegory");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("blogCalegory >=", value, "blogCalegory");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryLessThan(Integer value) {
            addCriterion("blogCalegory <", value, "blogCalegory");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryLessThanOrEqualTo(Integer value) {
            addCriterion("blogCalegory <=", value, "blogCalegory");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryIn(List<Integer> values) {
            addCriterion("blogCalegory in", values, "blogCalegory");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryNotIn(List<Integer> values) {
            addCriterion("blogCalegory not in", values, "blogCalegory");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryBetween(Integer value1, Integer value2) {
            addCriterion("blogCalegory between", value1, value2, "blogCalegory");
            return (Criteria) this;
        }

        public Criteria andBlogCalegoryNotBetween(Integer value1, Integer value2) {
            addCriterion("blogCalegory not between", value1, value2, "blogCalegory");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tblog
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 01 15:46:56 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tblog
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}