package cn.nnu.jyjs.etpweb.bean.Example;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("userName is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("userName is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("userName =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("userName <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("userName >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("userName >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("userName <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("userName <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("userName like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("userName not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("userName in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("userName not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("userName between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("userName not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUsereEmailIsNull() {
            addCriterion("usereEmail is null");
            return (Criteria) this;
        }

        public Criteria andUsereEmailIsNotNull() {
            addCriterion("usereEmail is not null");
            return (Criteria) this;
        }

        public Criteria andUsereEmailEqualTo(String value) {
            addCriterion("usereEmail =", value, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailNotEqualTo(String value) {
            addCriterion("usereEmail <>", value, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailGreaterThan(String value) {
            addCriterion("usereEmail >", value, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailGreaterThanOrEqualTo(String value) {
            addCriterion("usereEmail >=", value, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailLessThan(String value) {
            addCriterion("usereEmail <", value, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailLessThanOrEqualTo(String value) {
            addCriterion("usereEmail <=", value, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailLike(String value) {
            addCriterion("usereEmail like", value, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailNotLike(String value) {
            addCriterion("usereEmail not like", value, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailIn(List<String> values) {
            addCriterion("usereEmail in", values, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailNotIn(List<String> values) {
            addCriterion("usereEmail not in", values, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailBetween(String value1, String value2) {
            addCriterion("usereEmail between", value1, value2, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUsereEmailNotBetween(String value1, String value2) {
            addCriterion("usereEmail not between", value1, value2, "usereEmail");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("userPassword is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("userPassword is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("userPassword =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("userPassword <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("userPassword >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("userPassword >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("userPassword <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("userPassword <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("userPassword like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("userPassword not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("userPassword in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("userPassword not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("userPassword between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("userPassword not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNull() {
            addCriterion("userStatus is null");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNotNull() {
            addCriterion("userStatus is not null");
            return (Criteria) this;
        }

        public Criteria andUserStatusEqualTo(Integer value) {
            addCriterion("userStatus =", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotEqualTo(Integer value) {
            addCriterion("userStatus <>", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThan(Integer value) {
            addCriterion("userStatus >", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("userStatus >=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThan(Integer value) {
            addCriterion("userStatus <", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThanOrEqualTo(Integer value) {
            addCriterion("userStatus <=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusIn(List<Integer> values) {
            addCriterion("userStatus in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotIn(List<Integer> values) {
            addCriterion("userStatus not in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusBetween(Integer value1, Integer value2) {
            addCriterion("userStatus between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("userStatus not between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityIsNull() {
            addCriterion("userAuthority is null");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityIsNotNull() {
            addCriterion("userAuthority is not null");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityEqualTo(String value) {
            addCriterion("userAuthority =", value, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityNotEqualTo(String value) {
            addCriterion("userAuthority <>", value, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityGreaterThan(String value) {
            addCriterion("userAuthority >", value, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityGreaterThanOrEqualTo(String value) {
            addCriterion("userAuthority >=", value, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityLessThan(String value) {
            addCriterion("userAuthority <", value, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityLessThanOrEqualTo(String value) {
            addCriterion("userAuthority <=", value, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityLike(String value) {
            addCriterion("userAuthority like", value, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityNotLike(String value) {
            addCriterion("userAuthority not like", value, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityIn(List<String> values) {
            addCriterion("userAuthority in", values, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityNotIn(List<String> values) {
            addCriterion("userAuthority not in", values, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityBetween(String value1, String value2) {
            addCriterion("userAuthority between", value1, value2, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserAuthorityNotBetween(String value1, String value2) {
            addCriterion("userAuthority not between", value1, value2, "userAuthority");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlIsNull() {
            addCriterion("userHeadUrl is null");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlIsNotNull() {
            addCriterion("userHeadUrl is not null");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlEqualTo(String value) {
            addCriterion("userHeadUrl =", value, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlNotEqualTo(String value) {
            addCriterion("userHeadUrl <>", value, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlGreaterThan(String value) {
            addCriterion("userHeadUrl >", value, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlGreaterThanOrEqualTo(String value) {
            addCriterion("userHeadUrl >=", value, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlLessThan(String value) {
            addCriterion("userHeadUrl <", value, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlLessThanOrEqualTo(String value) {
            addCriterion("userHeadUrl <=", value, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlLike(String value) {
            addCriterion("userHeadUrl like", value, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlNotLike(String value) {
            addCriterion("userHeadUrl not like", value, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlIn(List<String> values) {
            addCriterion("userHeadUrl in", values, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlNotIn(List<String> values) {
            addCriterion("userHeadUrl not in", values, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlBetween(String value1, String value2) {
            addCriterion("userHeadUrl between", value1, value2, "userHeadUrl");
            return (Criteria) this;
        }

        public Criteria andUserHeadUrlNotBetween(String value1, String value2) {
            addCriterion("userHeadUrl not between", value1, value2, "userHeadUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tuser
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 01 15:46:56 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tuser
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}