package cn.nnu.jyjs.etpweb.mapper;

import cn.nnu.jyjs.etpweb.bean.Comment;
import cn.nnu.jyjs.etpweb.bean.Example.CommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    long countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int deleteByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int deleteByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    Comment selectByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomment
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int updateByPrimaryKey(Comment record);

    List<Comment> selectByBlogId(Integer blogId);
    List<Comment> selectByUserId(Integer userId);
    List<Comment> selectByParent(Integer parentId);
}