package cn.nnu.jyjs.etpweb.mapper;

import cn.nnu.jyjs.etpweb.bean.TagRelationship;
import cn.nnu.jyjs.etpweb.bean.Example.TagRelationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttagrelationship
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    long countByExample(TagRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttagrelationship
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int deleteByExample(TagRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttagrelationship
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int insert(TagRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttagrelationship
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int insertSelective(TagRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttagrelationship
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    List<TagRelationship> selectByExample(TagRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttagrelationship
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") TagRelationship record, @Param("example") TagRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttagrelationship
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    int updateByExample(@Param("record") TagRelationship record, @Param("example") TagRelationshipExample example);
}