server:
  port: 8080
  baseURL: locolhost
  session:
    timeout: 120

spring:
  datasource:
    name: blog
    url: jdbc:mysql://39.108.107.28:3306/eduTechPhen?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: SillyGoose4d.
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  thymeleaf:
    mode: HTML5
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.nnu.jyjs.etpweb

logging:
  file: log/info.log

file:
  upload: D:\webFile

#  config: classpath:slf4j.xml

#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql