server:
  port: 8080
  session:
    timeout: 120

spring:
  datasource:
    name: blog
    url: jdbc:mysql://39.108.107.28:3306/eduTechPhen?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: SillyGoose4d.
  thymeleaf:
    mode: HTML5

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.nnu.jyjs.etpweb

logging:
  file: log/info.log

file:
  upload: D:/webFile

#  config: classpath:slf4j.xml

#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql