package cn.nnu.jyjs.etpweb.bean;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomment.commentId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomment.blogId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomment.userId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomment.content
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomment.createT
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    @JSONField(format="yyyy-MM-dd HH:mm")        //转为JSON时按格式转换
    private Date createT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomment.parentId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomment.commentId
     *
     * @return the value of tcomment.commentId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomment.commentId
     *
     * @param commentId the value for tcomment.commentId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomment.blogId
     *
     * @return the value of tcomment.blogId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomment.blogId
     *
     * @param blogId the value for tcomment.blogId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomment.userId
     *
     * @return the value of tcomment.userId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomment.userId
     *
     * @param userId the value for tcomment.userId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomment.content
     *
     * @return the value of tcomment.content
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomment.content
     *
     * @param content the value for tcomment.content
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomment.createT
     *
     * @return the value of tcomment.createT
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Date getCreateT() {
        return createT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomment.createT
     *
     * @param createT the value for tcomment.createT
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setCreateT(Date createT) {
        this.createT = createT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomment.parentId
     *
     * @return the value of tcomment.parentId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomment.parentId
     *
     * @param parentId the value for tcomment.parentId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}