package cn.nnu.jyjs.etpweb.bean;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttags.tagId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttags.tagName
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private String tagName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttags.tagId
     *
     * @return the value of ttags.tagId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttags.tagId
     *
     * @param tagId the value for ttags.tagId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttags.tagName
     *
     * @return the value of ttags.tagName
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttags.tagName
     *
     * @param tagName the value for ttags.tagName
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }
}