package cn.nnu.jyjs.etpweb.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.userId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.userName
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.usereEmail
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private String usereEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.userPassword
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.userStatus
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.userAuthority
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private String userAuthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.userHeadUrl
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    private String userHeadUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.userId
     *
     * @return the value of tuser.userId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.userId
     *
     * @param userId the value for tuser.userId
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.userName
     *
     * @return the value of tuser.userName
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.userName
     *
     * @param userName the value for tuser.userName
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.usereEmail
     *
     * @return the value of tuser.usereEmail
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public String getUsereEmail() {
        return usereEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.usereEmail
     *
     * @param usereEmail the value for tuser.usereEmail
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setUsereEmail(String usereEmail) {
        this.usereEmail = usereEmail == null ? null : usereEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.userPassword
     *
     * @return the value of tuser.userPassword
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.userPassword
     *
     * @param userPassword the value for tuser.userPassword
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.userStatus
     *
     * @return the value of tuser.userStatus
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.userStatus
     *
     * @param userStatus the value for tuser.userStatus
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.userAuthority
     *
     * @return the value of tuser.userAuthority
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public String getUserAuthority() {
        return userAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.userAuthority
     *
     * @param userAuthority the value for tuser.userAuthority
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setUserAuthority(String userAuthority) {
        this.userAuthority = userAuthority == null ? null : userAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.userHeadUrl
     *
     * @return the value of tuser.userHeadUrl
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public String getUserHeadUrl() {
        return userHeadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.userHeadUrl
     *
     * @param userHeadUrl the value for tuser.userHeadUrl
     *
     * @mbg.generated Sat Sep 01 15:46:56 CST 2018
     */
    public void setUserHeadUrl(String userHeadUrl) {
        this.userHeadUrl = userHeadUrl == null ? null : userHeadUrl.trim();
    }
}